//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace registration.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GeneralInsuranceFinalEntities_ : DbContext
    {
        public GeneralInsuranceFinalEntities_()
            : base("name=GeneralInsuranceFinalEntities_")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminDetailsTable> AdminDetailsTables { get; set; }
        public virtual DbSet<MotorClaimDetailsTable> MotorClaimDetailsTables { get; set; }
        public virtual DbSet<MotorInsuranceTable> MotorInsuranceTables { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TransactionTable> TransactionTables { get; set; }
        public virtual DbSet<TravelClaimDetailsTable> TravelClaimDetailsTables { get; set; }
        public virtual DbSet<TravelInsuranceTable> TravelInsuranceTables { get; set; }
        public virtual DbSet<UserDetailsTable> UserDetailsTables { get; set; }
        public virtual DbSet<VehicleListTable> VehicleListTables { get; set; }
    
        public virtual ObjectResult<string> proc_AdminLoginCheck(string uid, string pswd)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            var pswdParameter = pswd != null ?
                new ObjectParameter("pswd", pswd) :
                new ObjectParameter("pswd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("proc_AdminLoginCheck", uidParameter, pswdParameter);
        }
    
        public virtual ObjectResult<string> proc_GetCarsOfManufacturer(string manu)
        {
            var manuParameter = manu != null ?
                new ObjectParameter("manu", manu) :
                new ObjectParameter("manu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("proc_GetCarsOfManufacturer", manuParameter);
        }
    
        public virtual ObjectResult<string> proc_GetManufacturers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("proc_GetManufacturers");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<Nullable<double>> proc_GetBrandNewPrice(string manu, string model)
        {
            var manuParameter = manu != null ?
                new ObjectParameter("manu", manu) :
                new ObjectParameter("manu", typeof(string));
    
            var modelParameter = model != null ?
                new ObjectParameter("model", model) :
                new ObjectParameter("model", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("proc_GetBrandNewPrice", manuParameter, modelParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> proc_GetLatestId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("proc_GetLatestId");
        }
    
        public virtual ObjectResult<Nullable<long>> proc_GetLatestTravelId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("proc_GetLatestTravelId");
        }
    
        public virtual ObjectResult<GetBrandNewPrice_Proc1_Result> GetBrandNewPrice_Proc1(Nullable<long> policyid, string manu, string model)
        {
            var policyidParameter = policyid.HasValue ?
                new ObjectParameter("policyid", policyid) :
                new ObjectParameter("policyid", typeof(long));
    
            var manuParameter = manu != null ?
                new ObjectParameter("manu", manu) :
                new ObjectParameter("manu", typeof(string));
    
            var modelParameter = model != null ?
                new ObjectParameter("model", model) :
                new ObjectParameter("model", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBrandNewPrice_Proc1_Result>("GetBrandNewPrice_Proc1", policyidParameter, manuParameter, modelParameter);
        }
    
        public virtual ObjectResult<Proc_MakeRenewalOfPolicy3_Result> Proc_MakeRenewalOfPolicy3(Nullable<long> policyid, Nullable<double> amount, Nullable<int> year)
        {
            var policyidParameter = policyid.HasValue ?
                new ObjectParameter("policyid", policyid) :
                new ObjectParameter("policyid", typeof(long));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(double));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_MakeRenewalOfPolicy3_Result>("Proc_MakeRenewalOfPolicy3", policyidParameter, amountParameter, yearParameter);
        }
    
        public virtual ObjectResult<Proj_Proc_UserPolicyDetailsDisplay2_Result> Proj_Proc_UserPolicyDetailsDisplay2(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proj_Proc_UserPolicyDetailsDisplay2_Result>("Proj_Proc_UserPolicyDetailsDisplay2", idParameter);
        }
    
        public virtual ObjectResult<proc_GetAllClaimsOfUser_Result> proc_GetAllClaimsOfUser(string mobile)
        {
            var mobileParameter = mobile != null ?
                new ObjectParameter("mobile", mobile) :
                new ObjectParameter("mobile", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetAllClaimsOfUser_Result>("proc_GetAllClaimsOfUser", mobileParameter);
        }
    
        public virtual ObjectResult<proc_GetAllPoliciesOfUser_Result> proc_GetAllPoliciesOfUser(string mobile)
        {
            var mobileParameter = mobile != null ?
                new ObjectParameter("mobile", mobile) :
                new ObjectParameter("mobile", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetAllPoliciesOfUser_Result>("proc_GetAllPoliciesOfUser", mobileParameter);
        }
    
        public virtual ObjectResult<proc_GetAllTravelClaimsOfUser_Result> proc_GetAllTravelClaimsOfUser(string mobile)
        {
            var mobileParameter = mobile != null ?
                new ObjectParameter("mobile", mobile) :
                new ObjectParameter("mobile", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetAllTravelClaimsOfUser_Result>("proc_GetAllTravelClaimsOfUser", mobileParameter);
        }
    
        public virtual ObjectResult<proc_GetAllTravelPoliciesOfUser_Result> proc_GetAllTravelPoliciesOfUser(string mobile)
        {
            var mobileParameter = mobile != null ?
                new ObjectParameter("mobile", mobile) :
                new ObjectParameter("mobile", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetAllTravelPoliciesOfUser_Result>("proc_GetAllTravelPoliciesOfUser", mobileParameter);
        }
    
        public virtual int proc_ApproveMotorClaim(Nullable<long> policyid, Nullable<int> amt, string admin)
        {
            var policyidParameter = policyid.HasValue ?
                new ObjectParameter("policyid", policyid) :
                new ObjectParameter("policyid", typeof(long));
    
            var amtParameter = amt.HasValue ?
                new ObjectParameter("amt", amt) :
                new ObjectParameter("amt", typeof(int));
    
            var adminParameter = admin != null ?
                new ObjectParameter("admin", admin) :
                new ObjectParameter("admin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_ApproveMotorClaim", policyidParameter, amtParameter, adminParameter);
        }
    
        public virtual ObjectResult<proc_GetMotorPolicy_Result> proc_GetMotorPolicy(Nullable<long> policy_id)
        {
            var policy_idParameter = policy_id.HasValue ?
                new ObjectParameter("policy_id", policy_id) :
                new ObjectParameter("policy_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetMotorPolicy_Result>("proc_GetMotorPolicy", policy_idParameter);
        }
    
        public virtual ObjectResult<proc_GetTravelPolicy_Result> proc_GetTravelPolicy(Nullable<long> policy_id)
        {
            var policy_idParameter = policy_id.HasValue ?
                new ObjectParameter("policy_id", policy_id) :
                new ObjectParameter("policy_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetTravelPolicy_Result>("proc_GetTravelPolicy", policy_idParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> proc_GetTransactionDetails(Nullable<long> policy_id)
        {
            var policy_idParameter = policy_id.HasValue ?
                new ObjectParameter("policy_id", policy_id) :
                new ObjectParameter("policy_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("proc_GetTransactionDetails", policy_idParameter);
        }
    
        public virtual ObjectResult<proc_GetMotor_Policy_Result> proc_GetMotor_Policy(Nullable<long> policy_id)
        {
            var policy_idParameter = policy_id.HasValue ?
                new ObjectParameter("policy_id", policy_id) :
                new ObjectParameter("policy_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetMotor_Policy_Result>("proc_GetMotor_Policy", policy_idParameter);
        }
    
        public virtual ObjectResult<proc_GetTravel_Policy_Result> proc_GetTravel_Policy(Nullable<long> policy_id)
        {
            var policy_idParameter = policy_id.HasValue ?
                new ObjectParameter("policy_id", policy_id) :
                new ObjectParameter("policy_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetTravel_Policy_Result>("proc_GetTravel_Policy", policy_idParameter);
        }
    
        public virtual ObjectResult<proc_Get_Policy_Motor_Result> proc_Get_Policy_Motor(Nullable<long> policy_id)
        {
            var policy_idParameter = policy_id.HasValue ?
                new ObjectParameter("policy_id", policy_id) :
                new ObjectParameter("policy_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Get_Policy_Motor_Result>("proc_Get_Policy_Motor", policy_idParameter);
        }
    
        public virtual ObjectResult<Proc_ValidateExistingAuthGuard3_Result> Proc_ValidateExistingAuthGuard3(string mob, string pass)
        {
            var mobParameter = mob != null ?
                new ObjectParameter("mob", mob) :
                new ObjectParameter("mob", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_ValidateExistingAuthGuard3_Result>("Proc_ValidateExistingAuthGuard3", mobParameter, passParameter);
        }
    
        public virtual ObjectResult<proc_Get_Policy_Travel_Result> proc_Get_Policy_Travel(Nullable<long> policy_id)
        {
            var policy_idParameter = policy_id.HasValue ?
                new ObjectParameter("policy_id", policy_id) :
                new ObjectParameter("policy_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Get_Policy_Travel_Result>("proc_Get_Policy_Travel", policy_idParameter);
        }
    
        public virtual int sp_insertMotorClaim(Nullable<long> policy_Id, string name, string mobile_Number, string reason, Nullable<System.DateTime> date_Of_Applying, Nullable<double> estimated_Amount_For_Repair, string license_Copy, string rC_Copy, string insurance_Copy, string bill_Copy, string authenticated_Letter_from_RTO, string claim_Status)
        {
            var policy_IdParameter = policy_Id.HasValue ?
                new ObjectParameter("Policy_Id", policy_Id) :
                new ObjectParameter("Policy_Id", typeof(long));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var mobile_NumberParameter = mobile_Number != null ?
                new ObjectParameter("Mobile_Number", mobile_Number) :
                new ObjectParameter("Mobile_Number", typeof(string));
    
            var reasonParameter = reason != null ?
                new ObjectParameter("Reason", reason) :
                new ObjectParameter("Reason", typeof(string));
    
            var date_Of_ApplyingParameter = date_Of_Applying.HasValue ?
                new ObjectParameter("Date_Of_Applying", date_Of_Applying) :
                new ObjectParameter("Date_Of_Applying", typeof(System.DateTime));
    
            var estimated_Amount_For_RepairParameter = estimated_Amount_For_Repair.HasValue ?
                new ObjectParameter("Estimated_Amount_For_Repair", estimated_Amount_For_Repair) :
                new ObjectParameter("Estimated_Amount_For_Repair", typeof(double));
    
            var license_CopyParameter = license_Copy != null ?
                new ObjectParameter("License_Copy", license_Copy) :
                new ObjectParameter("License_Copy", typeof(string));
    
            var rC_CopyParameter = rC_Copy != null ?
                new ObjectParameter("RC_Copy", rC_Copy) :
                new ObjectParameter("RC_Copy", typeof(string));
    
            var insurance_CopyParameter = insurance_Copy != null ?
                new ObjectParameter("Insurance_Copy", insurance_Copy) :
                new ObjectParameter("Insurance_Copy", typeof(string));
    
            var bill_CopyParameter = bill_Copy != null ?
                new ObjectParameter("Bill_Copy", bill_Copy) :
                new ObjectParameter("Bill_Copy", typeof(string));
    
            var authenticated_Letter_from_RTOParameter = authenticated_Letter_from_RTO != null ?
                new ObjectParameter("Authenticated_Letter_from_RTO", authenticated_Letter_from_RTO) :
                new ObjectParameter("Authenticated_Letter_from_RTO", typeof(string));
    
            var claim_StatusParameter = claim_Status != null ?
                new ObjectParameter("Claim_Status", claim_Status) :
                new ObjectParameter("Claim_Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insertMotorClaim", policy_IdParameter, nameParameter, mobile_NumberParameter, reasonParameter, date_Of_ApplyingParameter, estimated_Amount_For_RepairParameter, license_CopyParameter, rC_CopyParameter, insurance_CopyParameter, bill_CopyParameter, authenticated_Letter_from_RTOParameter, claim_StatusParameter);
        }
    
        public virtual int sp_insertTravelClaim(Nullable<long> travel_Policy_Id, string ticket_Copy, string reason_for_Claim, string mobile_Number, string claim_Status, string complaint_Copy)
        {
            var travel_Policy_IdParameter = travel_Policy_Id.HasValue ?
                new ObjectParameter("Travel_Policy_Id", travel_Policy_Id) :
                new ObjectParameter("Travel_Policy_Id", typeof(long));
    
            var ticket_CopyParameter = ticket_Copy != null ?
                new ObjectParameter("Ticket_Copy", ticket_Copy) :
                new ObjectParameter("Ticket_Copy", typeof(string));
    
            var reason_for_ClaimParameter = reason_for_Claim != null ?
                new ObjectParameter("Reason_for_Claim", reason_for_Claim) :
                new ObjectParameter("Reason_for_Claim", typeof(string));
    
            var mobile_NumberParameter = mobile_Number != null ?
                new ObjectParameter("Mobile_Number", mobile_Number) :
                new ObjectParameter("Mobile_Number", typeof(string));
    
            var claim_StatusParameter = claim_Status != null ?
                new ObjectParameter("Claim_Status", claim_Status) :
                new ObjectParameter("Claim_Status", typeof(string));
    
            var complaint_CopyParameter = complaint_Copy != null ?
                new ObjectParameter("Complaint_Copy", complaint_Copy) :
                new ObjectParameter("Complaint_Copy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insertTravelClaim", travel_Policy_IdParameter, ticket_CopyParameter, reason_for_ClaimParameter, mobile_NumberParameter, claim_StatusParameter, complaint_CopyParameter);
        }
    
        public virtual int proc_ApproveMotorClaim_Admin(Nullable<long> policyid, Nullable<int> amt, string admin)
        {
            var policyidParameter = policyid.HasValue ?
                new ObjectParameter("policyid", policyid) :
                new ObjectParameter("policyid", typeof(long));
    
            var amtParameter = amt.HasValue ?
                new ObjectParameter("amt", amt) :
                new ObjectParameter("amt", typeof(int));
    
            var adminParameter = admin != null ?
                new ObjectParameter("admin", admin) :
                new ObjectParameter("admin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_ApproveMotorClaim_Admin", policyidParameter, amtParameter, adminParameter);
        }
    
        public virtual int proc_ApproveMotorInsurance(Nullable<long> policyid, string admin)
        {
            var policyidParameter = policyid.HasValue ?
                new ObjectParameter("policyid", policyid) :
                new ObjectParameter("policyid", typeof(long));
    
            var adminParameter = admin != null ?
                new ObjectParameter("admin", admin) :
                new ObjectParameter("admin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_ApproveMotorInsurance", policyidParameter, adminParameter);
        }
    
        public virtual int proc_ApproveTravelClaim_Admin(Nullable<long> policyid, Nullable<int> amt, string admin)
        {
            var policyidParameter = policyid.HasValue ?
                new ObjectParameter("policyid", policyid) :
                new ObjectParameter("policyid", typeof(long));
    
            var amtParameter = amt.HasValue ?
                new ObjectParameter("amt", amt) :
                new ObjectParameter("amt", typeof(int));
    
            var adminParameter = admin != null ?
                new ObjectParameter("admin", admin) :
                new ObjectParameter("admin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_ApproveTravelClaim_Admin", policyidParameter, amtParameter, adminParameter);
        }
    
        public virtual int proc_ApproveTravelInsurance(Nullable<long> policyid, string admin)
        {
            var policyidParameter = policyid.HasValue ?
                new ObjectParameter("policyid", policyid) :
                new ObjectParameter("policyid", typeof(long));
    
            var adminParameter = admin != null ?
                new ObjectParameter("admin", admin) :
                new ObjectParameter("admin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_ApproveTravelInsurance", policyidParameter, adminParameter);
        }
    
        public virtual ObjectResult<proc_GetAllMotorClaim_Result> proc_GetAllMotorClaim()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetAllMotorClaim_Result>("proc_GetAllMotorClaim");
        }
    
        public virtual ObjectResult<proc_GetAllMotorInsurance_Result> proc_GetAllMotorInsurance()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetAllMotorInsurance_Result>("proc_GetAllMotorInsurance");
        }
    
        public virtual ObjectResult<proc_GetAllTravelClaim_Result> proc_GetAllTravelClaim()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetAllTravelClaim_Result>("proc_GetAllTravelClaim");
        }
    
        public virtual ObjectResult<proc_GetAllTravelInsurance_Result> proc_GetAllTravelInsurance()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetAllTravelInsurance_Result>("proc_GetAllTravelInsurance");
        }
    
        public virtual int proc_RejectMotorClaim(Nullable<long> policyid, Nullable<int> amt, string admin)
        {
            var policyidParameter = policyid.HasValue ?
                new ObjectParameter("policyid", policyid) :
                new ObjectParameter("policyid", typeof(long));
    
            var amtParameter = amt.HasValue ?
                new ObjectParameter("amt", amt) :
                new ObjectParameter("amt", typeof(int));
    
            var adminParameter = admin != null ?
                new ObjectParameter("admin", admin) :
                new ObjectParameter("admin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_RejectMotorClaim", policyidParameter, amtParameter, adminParameter);
        }
    
        public virtual int proc_RejectMotorInsurance(Nullable<long> policyid, string admin)
        {
            var policyidParameter = policyid.HasValue ?
                new ObjectParameter("policyid", policyid) :
                new ObjectParameter("policyid", typeof(long));
    
            var adminParameter = admin != null ?
                new ObjectParameter("admin", admin) :
                new ObjectParameter("admin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_RejectMotorInsurance", policyidParameter, adminParameter);
        }
    
        public virtual int proc_RejectTravelClaim(Nullable<long> policyid, Nullable<int> amt, string admin)
        {
            var policyidParameter = policyid.HasValue ?
                new ObjectParameter("policyid", policyid) :
                new ObjectParameter("policyid", typeof(long));
    
            var amtParameter = amt.HasValue ?
                new ObjectParameter("amt", amt) :
                new ObjectParameter("amt", typeof(int));
    
            var adminParameter = admin != null ?
                new ObjectParameter("admin", admin) :
                new ObjectParameter("admin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_RejectTravelClaim", policyidParameter, amtParameter, adminParameter);
        }
    
        public virtual int proc_RejectTravelInsurance(Nullable<long> policyid, string admin)
        {
            var policyidParameter = policyid.HasValue ?
                new ObjectParameter("policyid", policyid) :
                new ObjectParameter("policyid", typeof(long));
    
            var adminParameter = admin != null ?
                new ObjectParameter("admin", admin) :
                new ObjectParameter("admin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_RejectTravelInsurance", policyidParameter, adminParameter);
        }
    
        public virtual ObjectResult<proc_GetAllMotorClaim_Admin_Result> proc_GetAllMotorClaim_Admin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetAllMotorClaim_Admin_Result>("proc_GetAllMotorClaim_Admin");
        }
    
        public virtual ObjectResult<proc_GetAllMotorInsurance_Admin_Result> proc_GetAllMotorInsurance_Admin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetAllMotorInsurance_Admin_Result>("proc_GetAllMotorInsurance_Admin");
        }
    
        public virtual ObjectResult<proc_GetAllTravelClaim_Admin_Result> proc_GetAllTravelClaim_Admin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetAllTravelClaim_Admin_Result>("proc_GetAllTravelClaim_Admin");
        }
    
        public virtual ObjectResult<proc_GetAllTravelInsurance_Admin_Result> proc_GetAllTravelInsurance_Admin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetAllTravelInsurance_Admin_Result>("proc_GetAllTravelInsurance_Admin");
        }
    
        public virtual ObjectResult<proc_Get_Policy_Motor_Approved_Result> proc_Get_Policy_Motor_Approved(Nullable<long> policy_id)
        {
            var policy_idParameter = policy_id.HasValue ?
                new ObjectParameter("policy_id", policy_id) :
                new ObjectParameter("policy_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Get_Policy_Motor_Approved_Result>("proc_Get_Policy_Motor_Approved", policy_idParameter);
        }
    
        public virtual ObjectResult<proc_Get_Policy_Travel_Approved_Result> proc_Get_Policy_Travel_Approved(Nullable<long> policy_id)
        {
            var policy_idParameter = policy_id.HasValue ?
                new ObjectParameter("policy_id", policy_id) :
                new ObjectParameter("policy_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Get_Policy_Travel_Approved_Result>("proc_Get_Policy_Travel_Approved", policy_idParameter);
        }
    }
}
